/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  darkMode: 'class',
  theme: {
    borderRadius: {
      DEFAULT: "0px", sm: "0px", md: "0px",
      lg: "0px", xl: "0px", "2xl": "0px", full: "0px",
    },
    colors: {
      "primary":                    "#ffffff",
      "on-primary":                 "#1a1c1c",
      "primary-container":          "#d4d4d4",
      "on-primary-container":       "#000000",
      "on-primary-fixed":           "#ffffff",
      "on-primary-fixed-variant":   "#e2e2e2",
      "secondary":                  "#c7c6c6",
      "on-secondary":               "#1a1c1c",
      "secondary-container":        "#464747",
      "on-secondary-container":     "#e3e2e2",
      "tertiary":                   "#e4e2e2",
      "on-tertiary":                "#1b1c1c",
      "tertiary-container":         "#919090",
      "on-tertiary-container":      "#000000",
      "error":                      "#ffb4ab",
      "on-error":                   "#690005",
      "error-container":            "#93000a",
      "on-error-container":         "#ffdad6",
      "background":                 "#131313",
      "on-background":              "#e2e2e2",
      "surface":                    "#131313",
      "surface-dim":                "#131313",
      "surface-bright":             "#393939",
      "surface-container-lowest":   "#0e0e0e",
      "surface-container-low":      "#1b1b1b",
      "surface-container":          "#1f1f1f",
      "surface-container-high":     "#2a2a2a",
      "surface-container-highest":  "#353535",
      "surface-variant":            "#353535",
      "on-surface":                 "#e2e2e2",
      "on-surface-variant":         "#c6c6c6",
      "outline":                    "#919191",
      "outline-variant":            "#474747",
      "inverse-surface":            "#e2e2e2",
      "inverse-on-surface":         "#303030",
      "inverse-primary":            "#5d5f5f",
      "surface-tint":               "#c6c6c7",
    },
    extend: {
      fontFamily: {
        mono:     ["JetBrains Mono", "monospace"],
        headline: ["JetBrains Mono", "monospace"],
        body:     ["JetBrains Mono", "monospace"],
        label:    ["JetBrains Mono", "monospace"],
      },
      boxShadow: {
        hard: "4px 4px 0 rgba(0,0,0,0.4)",
      },
    },
  },
  plugins: [],
}
